# Generated by Django 4.2.4 on 2023-08-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stage',
            field=models.CharField(choices=[('Required', 'Required'), ('Production', 'Production'), ('Finished', 'Finished')], default=('Required', 'Required'), max_length=15),
        ),
    ]
